name: fetch-prices
on:
  schedule:
    - cron: "0 7,19 * * *"    # 2x/jour en UTC
  workflow_dispatch:          # bouton "Run workflow" manuel

permissions:
  contents: write             # pour pousser une branche
  pull-requests: write        # pour ouvrir/mettre à jour un PR

concurrency:
  group: cs2-data-update
  cancel-in-progress: true    # évite 2 runs qui se chevauchent

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # récupère tout l'historique (utile pour PR)

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Fetch prices (append CSV)
        env:
          CSFLOAT_API_KEY: ${{ secrets.CSFLOAT_API_KEY }}
        run: |
          python fetch_prices.py

      # ↙️ ICI on ne push PAS sur main.
      # On crée / met à jour un Pull Request depuis une branche bot.
      - name: Create/Update Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore(data): update price_history.csv"
          body: "Automated data update (CSFloat) – append latest prices."
          commit-message: "chore(data): update price_history.csv [skip ci]"
          branch: "bot/data-update"
          delete-branch: true
          add-paths: |
            data/price_history.csv
