name: fetch-prices
on:
  schedule:
    - cron: "0 7,19 * * *"   # 2x/jour (ne s'exécute que sur la branche par défaut du repo)
  workflow_dispatch:         # exécution manuelle (ou via l'app Streamlit)

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch-multi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run fetch for each profile
        env:
          CSFLOAT_API_KEY: ${{ secrets.CSFLOAT_API_KEY }}
        run: |
          for d in data/*; do
            if [ -f "$d/holdings.csv" ]; then
              echo "=== Processing $d ==="
              python fetch_prices.py "$d/holdings.csv" || true
            fi
          done

      - name: Commit & push
        run: |
          echo "Pushing to branch: ${{ github.ref_name }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*/price_history.csv
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "update price history for all profiles [skip ci]"
            git push origin "${{ github.ref_name }}"
          fi

