name: fetch-prices
on:
  push:
    paths:
      - 'data/holdings.csv'   # relance si tu modifies ta liste d'items
  schedule:
    - cron: "0 7,19 * * *"    # 2x/jour en UTC (~09h & 21h en Europe/Prague)
  workflow_dispatch:          # bouton manuel "Run workflow"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: cs2-data-update
  cancel-in-progress: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show current holdings.csv (debug)
        run: |
          echo "---- data/holdings.csv ----"
          if [ -f data/holdings.csv ]; then
            nl -ba data/holdings.csv
          else
            echo "MISSING: data/holdings.csv"
          fi
          echo "---------------------------"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Fetch prices (append CSV)
        env:
          CSFLOAT_API_KEY: ${{ secrets.CSFLOAT_API_KEY }}
        run: |
          python fetch_prices.py

      # 1) Crée/met à jour le PR avec ton token personnel (GH_PAT)
      - name: Create/Update Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          title: "chore(data): update price_history.csv"
          body: "Automated data update (CSFloat) – append latest prices."
          commit-message: "chore(data): update price_history.csv [skip ci]"
          branch: "bot/data-update"
          delete-branch: true
          add-paths: |
            data/price_history.csv

      # 2) Merge automatiquement le PR créé (si quelque chose a changé)
      - name: Auto-merge PR
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          pull-request: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
          commit-message: pull-request-title
          delete-branch: true
