name: fetch-prices

on:
  schedule:
    - cron: '0 7,19 * * *'   # 07:00 & 19:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-multi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          set -euo pipefail
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run fetch for each profile
        env:
          CSFLOAT_API_KEY: ${{ secrets.CSFLOAT_API_KEY }}
        run: |
          set -euo pipefail
          shopt -s nullglob
          for d in data/*; do
            [ -d "$d" ] || continue
            echo "=============================="
            echo ">>> Processing profile: $(basename "$d")"
            echo "=============================="
            if [ -f "$d/holdings.csv" ]; then
              echo "head -n 5 $d/holdings.csv:"
              head -n 5 "$d/holdings.csv" || true

              echo "Running: python fetch_prices.py '$d/holdings.csv'"
              python fetch_prices.py "$d/holdings.csv" || true

              if [ -f "$d/price_history.csv" ]; then
                rows=$(( $(wc -l < "$d/price_history.csv") - 1 ))
                echo "[INFO] $(basename "$d"): price_history.csv has ${rows} data rows."
              else
                echo "[WARN] $(basename "$d"): price_history.csv not created."
              fi
            else
              echo "[SKIP] $d/holdings.csv not found"
            fi
          done

      - name: Commit & push
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f data/*/price_history.csv || true

          echo "=== staged diff ==="
          git diff --cached --stat || true

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "update price history for all profiles [skip ci]"
            CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
            echo "Pushing to ${CURRENT_BRANCH}"
            git push origin "${CURRENT_BRANCH}"
          fi
